import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ConfigProvider } from 'antd';
import "./globals.css";
import ChatSupportBubble from '@/components/ChatSupportBubble';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AutoHunt - Selling Car",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning={true}
    >
      <body
        className="antialiased"
        suppressHydrationWarning={true}
      >
        <ConfigProvider>
          {children}
          <ChatSupportBubble />
        </ConfigProvider>
      </body>
    </html>
  );
}
