// This file is auto-generated by scripts/generate-voice-routes.js
// Do not edit manually.

export type VoiceRouteRecord = {
  path: string;
  title: string;
  keywords: string[];
};

export const VOICE_ROUTES: VoiceRouteRecord[] = [
  {
    "path": "/",
    "title": "Home",
    "keywords": [
      "home"
    ]
  },
  {
    "path": "/about",
    "title": "About",
    "keywords": [
      "about"
    ]
  },
  {
    "path": "/admin/cars",
    "title": "Admin / Cars",
    "keywords": [
      "admin",
      "cars"
    ]
  },
  {
    "path": "/admin/cars/posting",
    "title": "Admin / Cars / Posting",
    "keywords": [
      "admin",
      "cars",
      "posting"
    ]
  },
  {
    "path": "/admin/cars/reviews",
    "title": "Admin / Cars / Reviews",
    "keywords": [
      "admin",
      "cars",
      "reviews"
    ]
  },
  {
    "path": "/admin/coupons",
    "title": "Admin / Coupons",
    "keywords": [
      "admin",
      "coupons"
    ]
  },
  {
    "path": "/admin/customers",
    "title": "Admin / Customers",
    "keywords": [
      "admin",
      "customers"
    ]
  },
  {
    "path": "/admin/dashboard",
    "title": "Admin / Dashboard",
    "keywords": [
      "admin",
      "dashboard"
    ]
  },
  {
    "path": "/admin/finance",
    "title": "Admin / Finance",
    "keywords": [
      "admin",
      "finance"
    ]
  },
  {
    "path": "/admin/notifications",
    "title": "Admin / Notifications",
    "keywords": [
      "admin",
      "notifications"
    ]
  },
  {
    "path": "/admin/orders",
    "title": "Admin / Orders",
    "keywords": [
      "admin",
      "orders"
    ]
  },
  {
    "path": "/admin/support",
    "title": "Admin / Support",
    "keywords": [
      "admin",
      "support"
    ]
  },
  {
    "path": "/admin/transactions",
    "title": "Admin / Transactions",
    "keywords": [
      "admin",
      "transactions"
    ]
  },
  {
    "path": "/careers",
    "title": "Careers",
    "keywords": [
      "careers"
    ]
  },
  {
    "path": "/contact",
    "title": "Contact",
    "keywords": [
      "contact"
    ]
  },
  {
    "path": "/cookies",
    "title": "Cookies",
    "keywords": [
      "cookies"
    ]
  },
  {
    "path": "/login",
    "title": "Login",
    "keywords": [
      "login"
    ]
  },
  {
    "path": "/messages",
    "title": "Messages",
    "keywords": [
      "messages"
    ]
  },
  {
    "path": "/orders",
    "title": "Orders",
    "keywords": [
      "orders"
    ]
  },
  {
    "path": "/orders/seller",
    "title": "Orders / Seller",
    "keywords": [
      "orders",
      "seller"
    ]
  },
  {
    "path": "/privacy",
    "title": "Privacy",
    "keywords": [
      "privacy"
    ]
  },
  {
    "path": "/profile",
    "title": "Profile",
    "keywords": [
      "profile"
    ]
  },
  {
    "path": "/sell",
    "title": "Sell",
    "keywords": [
      "sell"
    ]
  },
  {
    "path": "/signup",
    "title": "Signup",
    "keywords": [
      "signup"
    ]
  },
  {
    "path": "/support",
    "title": "Support",
    "keywords": [
      "support"
    ]
  },
  {
    "path": "/support/requests",
    "title": "Support / Requests",
    "keywords": [
      "support",
      "requests"
    ]
  },
  {
    "path": "/terms",
    "title": "Terms",
    "keywords": [
      "terms"
    ]
  },
  {
    "path": "/vehicles",
    "title": "Vehicles",
    "keywords": [
      "vehicles"
    ]
  },
  {
    "path": "/vehicles/ai-consultant",
    "title": "Vehicles / Ai consultant",
    "keywords": [
      "vehicles",
      "ai",
      "consultant"
    ]
  },
  {
    "path": "/vehicles/ai-finder",
    "title": "Vehicles / Ai finder",
    "keywords": [
      "vehicles",
      "ai",
      "finder"
    ]
  }
] as const;
